# ML Model Configuration for Famiglia Routes

[models]
# Path to trained ONNX models (relative to this file)
traffic_predictor = "../models/production/traffic_speed_predictor_v1.onnx"
route_time_predictor = "../models/production/route_time_predictor_v1.onnx"

[inference]
# ONNX Runtime configuration
threads = 4
optimization_level = 3  # 0=None, 1=Basic, 2=Extended, 3=All
use_gpu = false

[features]
# Feature flags for ML capabilities
enable_traffic_prediction = true
enable_time_prediction = true
fallback_to_baseline = true  # Use baseline optimizer if models fail to load

[performance]
# Performance tuning
max_batch_size = 32
cache_predictions = true
cache_ttl_seconds = 300  # 5 minutes

[logging]
# Logging configuration
log_predictions = false
log_inference_time = true
