pub mod federated;
pub mod federated_http;
pub mod fusion_engine;
pub mod gpu_optimizer;
pub mod hardware_detector;
pub mod jit;
pub mod jit_codegen;
pub mod jit_executor;
pub mod kernel_registry;
pub mod orchestrator;
pub mod performance_db;
pub mod prime_optimizer;
pub mod profiler;
pub mod runtime_profiler;
pub mod selector;

pub use federated::{AggregatedKnowledge, FederatedLearningEngine, PeerConnection};
pub use federated_http::{SyncRequest, SyncResponse, start_http_server};
pub use fusion_engine::{FusionEngine, FusionOp, FusionPattern};
pub use gpu_optimizer::{GpuOptimizer, GpuInfo, KernelConfig, MatmulConfig, ConvConfig};
pub use hardware_detector::{HardwareInfo, CpuVendor, Platform};
pub use jit::{JITCompiler, OptimizationLevel, WorkloadSignature};
pub use jit_codegen::{X86CodeGenerator, generate_gemm_kernel};
pub use jit_executor::JITExecutor;
pub use kernel_registry::{KernelRegistry, KernelType};
pub use orchestrator::AdaptiveKernelOrchestrator;
pub use performance_db::{PerformanceVector, PerformanceVectorDB};
pub use prime_optimizer::{PrimeConfig, PrimeOptimizer, OptimizationResult};
pub use profiler::{HardwareProfiler, WorkloadFeatures};
pub use runtime_profiler::{RuntimeProfiler, AdaptiveOptimizer, PerformanceMetrics};
pub use selector::KernelSelector;
